sudo : required
language: generic 
services:
 - docker

before_install:
 - docker build -t dibzjr/docker-react -f Dockerfile.dev . 


scripts:
 - docker run -e CI=true dibzjr/docker-react npm run test -- --coverage   
